# Default values for ibm-microservice-builder fabric.

# zipkin section defines all of the values that can be overridden in the zipkin subchart which is included in fabric chart
zipkin:
  
  # The number of replica instances for the Zipkin deployment; this should only be increased above one if Elasticsearch is being used rather than in-memory storage
  replicaCount: 1
  
  # Proportion of traces for Zipkin to retain; between 0.0 (none) and 1.0 (all)
  collectorSampleRatePct: 1.0
  
  # The Java options that are used for the Zipkin process
  javaOpts: "-Xmx512m"
  
  # A comma-separated list of Elasticsearch base URLs to provide persistence for Zipkin; defaults to in-memory storage if not set
  elasticsearchHosts: ""

  # service section defines the overrides that can be set for the zipkin service resource that is created in the zipkin subchart
  service:
  
    # The name that is used for the Kubernetes service fronting the Zipkin deployment
    name: "zipkin"
    
    # The default type of service that is created for zipkin
    type: "ClusterIP"
    
    # The default service port for the zipkin service  
    port: 30411
    
# SecretGenerator section defines the image and tag pulled and used to generate the Liberty secrets
secretGenerator:
  image: mycluster.icp:8500/default/ibmcom/mb-tools
  imageTag: 2.1.0

# Name of secret containing credentials for retrieving Docker images
global:
  imagePullSecret:
    name:
