name: ibm-icplogging
version: 0.9.7
description: Log storage and search management solution
home: https://elastic.co
icon: https://static-www.elastic.co/assets/blt9a26f88bfbd20eb5/icon-elasticsearch-bb.svg?q=423
sources:
  - https://github.com/elastic/
maintainers:
  - name: Elastic
  - name: IBM
tillerVersion: ">=2.4.0"
