apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.kibana.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ .Values.kibana.name }}-config
  namespace: {{ .Values.kibana.namespace }}
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    server.port: "{{ .Values.kibana.internal }}"
    elasticsearch.url: "{{ .Values.kibana.elasticsearch.url }}"
    xpack.monitoring.enabled: {{ .Values.xpack.monitoring }}
    xpack.security.enabled: {{ .Values.xpack.security }}
    xpack.graph.enabled: {{ .Values.xpack.graph }}
    xpack.reporting.enabled: {{ .Values.xpack.reporting }}
    xpack.ml.enabled: {{ .Values.xpack.ml }}
