apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.kibana.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.kibana.namespace }}
spec:
  selector:
    app: {{ .Values.kibana.name }}
    component: {{ .Values.kibana.name }}
  ports:
  - port: {{ .Values.kibana.internal }}
    nodePort: {{ .Values.kibana.external }}
    protocol: TCP
    targetPort: {{ .Values.kibana.internal }}
  type: LoadBalancer
