###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation
###############################################################################
apiVersion: v1
description: Installs Kibana, a web UI to query and visualize data in existing Elasticsearch clusters
name: ibm-icplogging-kibana
version: 0.1.0
tillerVersion: ">=2.5.0"
