###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation
###############################################################################
image:
  pullPolicy: IfNotPresent

kibana:
  replicas: 1
  name: kibana
  namespace: kube-system
  internal: 5601
  external: 32601
  elasticsearch:
    url: http://elasticsearch:9200
  image:
    repository: mycluster.icp:8500/default/ibmcom/kibana
    tag: 5.5.1
  managementNodeOnly: false

xpack:
  monitoring: false
  security: false
  graph: false
  reporting: false
  ml: false
