apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-github-secrets
  labels:
    app: {{ template "fullname" . }}  
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
type: Opaque
data:
  oauth-token: {{ default "MISSING" .Values.GitHub.OAuth.Token | b64enc | quote }}
  app-id: {{ default "MISSING" .Values.GitHub.App.Id | b64enc | quote }}
  app-secret: {{ default "MISSING" .Values.GitHub.App.Secret | b64enc | quote }}
