{{- if .Values.Master.HostName }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.Master.Ingress.Annotations }}
  annotations:
{{ toYaml .Values.Master.Ingress.Annotations | indent 4 }}
{{- end }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}  
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}" 
spec:
  rules:
  - host: {{ .Values.Master.HostName | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.Master.ServicePort }}
{{- if .Values.Master.Ingress.TLS }}
  tls:
{{ toYaml .Values.Master.Ingress.TLS | indent 4 }}
{{- end -}}
{{- end }}
