{{- if .Values.Pipeline.Maven.MirrorUrl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-maven-settings
  labels:
    app: {{ template "fullname" . }}  
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
data:
  settings.xml: |-
    <settings>
      <mirrors>
        <mirror>
          <id>proxy</id>
          <mirrorOf>{{.Values.Pipeline.Maven.MirrorOf}}</mirrorOf>
          <url>{{.Values.Pipeline.Maven.MirrorUrl}}</url>
        </mirror>
      </mirrors>
    </settings>
{{- end -}}
