apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: default
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}  
    release: {{.Release.Name | quote }}
    heritage: {{.Release.Service | quote }} 
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 9411
    {{/* nodePort is an optional value that is not used when type is ClusterIP */}}
    {{ if (ne .Values.service.type "ClusterIP") }}
    nodePort: {{ .Values.service.port }}
    {{end}}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
