apiVersion: batch/v1
kind: Job
metadata:
  name: secret-generator-deploy
  labels:
    app: {{ template "fullname" . }}  
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"  
spec:
  template:
    metadata:
      name: secret-generator-deploy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: secret-generator-deploy
        image: "{{.Values.secretGenerator.image}}:{{.Values.secretGenerator.imageTag}}"
      {{- if .Values.global.imagePullSecret }}
        {{- if .Values.global.imagePullSecret.name }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret.name }}
        {{- end }}
      {{- end }}
      restartPolicy: Never

