apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.elasticsearch.client.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "client.fullname" . }}
spec:
  replicas: {{ .Values.elasticsearch.client.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.fullname" . }}
        component: {{ .Values.elasticsearch.client.name }}
        release: {{ .Release.Name }}
        role: client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      {{- if eq .Values.elasticsearch.client.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "elasticsearch.fullname" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.elasticsearch.client.name }}"
      {{- else if eq .Values.elasticsearch.client.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "elasticsearch.fullname" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.elasticsearch.client.name }}"
      {{- end }}
      initContainers:
      - name: "sysctl"
        image: "{{ .Values.elasticsearch.initImage.repository }}:{{ .Values.elasticsearch.initImage.tag }}"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/sh", "-c", "sysctl -w vm.max_map_count=262144 && sed -i '/^vm.max_map_count /d' /etc/sysctl.conf && echo 'vm.max_map_count = 262144' >> /etc/sysctl.conf"]
        securityContext:
          privileged: true
      containers:
      - name: indices-cleaner
        image: {{ .Values.curator.image.repository }}:{{ .Values.curator.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: actionfile
          mountPath: /action.yml
          subPath: action.yml
        - name: localtime
          mountPath: "/etc/localtime"
          readOnly: true
        - name: curator-config
          mountPath: /etc/curator.yml
          subPath: curator.yml
        - name: cron
          mountPath: /etc/cron.d/curator-cron
          subPath: curator-cron
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.elasticsearch.client.memoryLimit }}
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms{{ .Values.elasticsearch.client.heapSize }} -Xmx{{ .Values.elasticsearch.client.heapSize }}"
        ports:
        - containerPort: {{ .Values.elasticsearch.client.restPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.elasticsearch.internalPort }}
          name: transport
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
          - emptyDir:
              medium: ""
            name: data
          - name: es-config
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-config
              items:
                - key: client.yml
                  path: elasticsearch.yml
          - name: "actionfile"
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-curator-config
              items:
                - key: action.yml
                  path: action.yml
          - name: "localtime"
            hostPath:
              path: /etc/localtime
          - name: "curator-config"
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-curator-config
              items:
                - key: config.yml
                  path: curator.yml
          - name: "cron"
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-curator-config
              items:
                - key: cron
                  path: curator-cron
