apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-config
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.elasticsearch.data.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  master.yml: |-
    cluster.name: "{{ .Values.elasticsearch.name }}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: {{ .Values.elasticsearch.master.name }}-discovery
    discovery.zen.minimum_master_nodes: {{ .Values.elasticsearch.master.replicas }}
    xpack.monitoring.enabled: {{ .Values.xpack.monitoring }}    
    xpack.security.enabled: {{ .Values.xpack.security }}
    xpack.ml.enabled: {{ .Values.xpack.ml }}
    xpack.watcher.enabled: {{ .Values.xpack.watcher }}
    node.master: true
    node.data: false
    http.enabled: false
    transport.tcp.port: {{ .Values.elasticsearch.internalPort }}

  data.yml: |-
    cluster.name: "{{ .Values.elasticsearch.name }}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: {{ .Values.elasticsearch.master.name }}-discovery
    discovery.zen.minimum_master_nodes: {{ .Values.elasticsearch.master.replicas }}
    xpack.monitoring.enabled: {{ .Values.xpack.monitoring }}    
    xpack.security.enabled: {{ .Values.xpack.security }}
    xpack.watcher.enabled: {{ .Values.xpack.watcher }}
    node.master: false
    node.data: true
    http.enabled: false
    transport.tcp.port: {{ .Values.elasticsearch.internalPort }}

  client.yml: |-
    cluster.name: "{{ .Values.elasticsearch.name }}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: {{ .Values.elasticsearch.master.name }}-discovery
    discovery.zen.minimum_master_nodes: {{ .Values.elasticsearch.master.replicas }}
    xpack.monitoring.enabled: {{ .Values.xpack.monitoring }}    
    xpack.security.enabled: {{ .Values.xpack.security }}
    xpack.watcher.enabled: {{ .Values.xpack.watcher }}
    node.master: false
    node.data: false
    http.enabled: true
    transport.tcp.port: {{ .Values.elasticsearch.internalPort }}
    http.port: {{ .Values.elasticsearch.client.restPort }}
