apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.elasticsearch.master.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    role: master
  name: {{ .Values.elasticsearch.master.name }}-discovery
spec:
  type: ClusterIP
  selector:
    app: {{ template "elasticsearch.fullname" . }}
    component: "{{ .Values.elasticsearch.master.name }}"
    release: {{ .Release.Name }}
    role: master
  ports:
  - name: transport
    port: {{ .Values.elasticsearch.internalPort }}
    targetPort: {{ .Values.elasticsearch.internalPort }}
    protocol: TCP
