apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.elasticsearch.client.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.elasticsearch.name }}
spec:
  type: {{ .Values.elasticsearch.client.serviceType }}
  selector:
    app: {{ template "elasticsearch.fullname" . }}
    component: {{ .Values.elasticsearch.client.name }}
    release: {{ .Release.Name }}
    role: client
  ports:
  - name: http
    port: {{ .Values.elasticsearch.client.restPort }}
    targetPort: {{ .Values.elasticsearch.client.restPort }}
    protocol: TCP
