apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "kibana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ .Values.kibana.name }}
spec:
  ports:
  - port: {{ .Values.kibana.internal }}
    protocol: TCP
    targetPort: ui
    nodePort: {{ .Values.kibana.external }}
  selector:
    app: {{ template "name" . }}
    component: {{ .Values.kibana.name }}
    release: {{ .Release.Name }}
  type: LoadBalancer
