apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "logstash.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.logstash.name }}"
    release: {{ .Release.Name }}
    heritage: "{{ .Release.Service }}"
  name: {{ template "logstash.fullname" . }}
spec:
  replicas: {{ .Values.logstash.replicas }}
  selector:
    matchLabels:
      name: logstash
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 3
  minReadySeconds: 5
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: logstash
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx{{ .Values.logstash.heapSize }} -Xms{{ .Values.logstash.heapSize }}
        image: {{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}
        name: logstash
        resources:
          limits:
            memory: {{ .Values.logstash.memoryLimit }}
        ports:
        - containerPort: {{ .Values.logstash.port }}
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline
          name: pipeline-config
        - mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          name: logstash-config
        - name: data
          mountPath: /usr/share/logstash/data
{{ if .Values.logstash.probe.enabled }}
        livenessProbe:
          httpGet:
            path: /logstash/health
            port: 9601
          initialDelaySeconds: 300
          periodSeconds: {{ .Values.logstash.probe.periodSeconds }}
      - name: logstash-liveness-probe
        image: {{ .Values.logstash.probe.image.repository }}:{{ .Values.logstash.probe.image.tag }}
        volumeMounts:
        - mountPath: /opt/ibm/logstash-liveness-probe/config/app.json
          subPath: app.json
          name: probe-config
{{ end }}
      restartPolicy: Always
      volumes:
      - name: pipeline-config
        configMap:
          name: {{ template "logstash.fullname" . }}-config
          items:
          - key: k8s.conf
            path: k8s.conf
      - name: logstash-config
        configMap:
          name: {{ template "logstash.fullname" . }}-config
          items:
          - key: logstash.yml
            path: logstash.yml
{{ if .Values.logstash.probe.enabled }}
      - name: probe-config
        configMap:
          name: {{ template "logstash.fullname" . }}-config
          items:
          - key: app.json
            path: app.json
{{ end }}
      - emptyDir:
          medium: ""
        name: data
status: {}
