apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "logstash.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.logstash.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ .Values.logstash.name }}
spec:
  ports:
  - name: "beats"
    port: {{ .Values.logstash.port }}
    targetPort: {{ .Values.logstash.port }}
  selector:
    name: {{ .Values.logstash.name }}
